### ISSUE TITLE
api-01-local-function / local api function call

### ISSUE THREAD

**Issue by nmadadair** [TwilioQuest/twilioquest-api-academy#35]
- [x] objective.json
- [x] description.md
- [x] validator.js
- [x] walkthrough.md

For more details, reference the [original objective planning doc](https://docs.google.com/document/d/1Esz69gd10vK4Btnk_pn0pmKTUgIq9f7sCrmnMVyOt5E/edit#heading=h.uoyv4k1cq39u).

## Objective outline
- This is the first step in learning how to craft the Divination spell
- Spells are crafted by passing data around? 
- Intro APIs as a local function call of `String.replaceAll()`
- Write a QuestIDE function that turns all instance of "word1" with "word2" 
  - What is our divination/API themed phrase and keywords to replace?
  - Probably we want a few different phrases as test cases to avoid hard coding

**Comment by MarvelProgramming** [comment]
@rmkubik @nmadadair Looks like if we want to use the `String.replaceAll` method, we'd need to upgrade Electron. It wasn't added until [node 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#:~:text=Toggle%20history-,15.0.0,-Toggle%20history), and the [Electron version TQ is on uses node 12.13.0](https://releases.electronjs.org/release/v8.2.4#:~:text=80.0.3987.165-,12.13.0,-8.0.426.27%2Delectron.0). Alternatively, we could always use another method or write our own replaceAll implementation to avoid the trouble

**Comment by joenash** [comment]
Writing our own `replaceAll` might be interesting if that import can be explicit in the QuestIDE code, as a illustration that the functions a library author exposes are also an API. To fit with the spell construction theming, maybe they're importing from `spellbook`, and any helper functions we write (for example, later on we may have some helpers to interact with the APIs we're creating for this) also go in `spellbook`.

**Comment by joenash** [comment]
Regarding the objective outline:

> Spells are crafted by passing strings around?

What is "spell" a metaphor for in the API Academy/what concept is it abstracting? My read is that it's quite a loose metaphor for a program that interacts with an API. If that's correct, we probably shouldn't tie it too strongly to a particular type of data. For example the web APIs are going to be returning JSON, and because Javascript is ~terrible~ interesting, sometimes things are strings when you don't expect them to be or not strings when you do expect them to be and we probably shouldn't invite learners to look too closely at that in this mission.

**Comment by rmkubik** [comment]
Yeah, I think that's fine! I just wanted to see a narrative idea of like "you write magical spells by passing data around" between different APIs.

Instead of Data Plumber you get to become a Data Magician.

**Comment by rmkubik** [comment]
I think I specifically wrote "string" there since plaintext web requests are "stringified" before you send them... But I think it's a good shout that thinking about them as "strings" is a bad thing to teach. They're just a bundled of ??? data that you need to interpret into something meaningful on either end of the request (like JSON or form data or gql).

**Comment by rmkubik** [comment]
Can you investigate what it would take to actually import a library in our example code @MarvJohnson?

The only things I know we import are full on published NPM modules and library built ins... We could certainly think about publishing a module for this. Or doing a local import, but I don't know what our options are off the top of my head. It's important to check that any import works both when running it in the QuestIDE _and_ via Validator Hack execution. 

Currently, those 2 systems evaluate in different methods! So sometimes a thing will work in one, but not the other.

**Comment by nmadadair** [comment]
What kind of writing content do we need for the spellbook? I've been putting together some notes on divination generally that could be used in these objectives. I could put together some short sentences/paragraphs on definitions of divination / types of divination methods / history of divination methods, etc. Does that form/content work for these objectives?

**Comment by rmkubik** [comment]
@nmadadair  Ah, in this context, the "spellbook" would be a programatic API! 

For the actual text content that could be useful is something like a thematic incantation line (or a few lines). We would have the players run their function with these text lines as input. 

I googled "poem incantation" and copied one that seemed interesting:
>      Invoke, People of the Sea, invoke the poet, that he may
>        compose a spell for you.
>     For I, the Druid, who set out letters in Ogham, I, who part
>        combatants,
>     I will approach the rath of the Sidhe to seek a cunning poet
>        that together we may concoct incantations.
>     I am a wind of the sea.

I think we'd want something like this, but programming and API themed. And then it would have words like "confusion" in it and we'd want to replaced them with "communication". Or "discord" replaced with "harmony". That sort of thing. Happy to help brainstorm on this one if this is a wild ask haha

**Comment by nmadadair** [comment]
@rmkubik Ah, this is very helpful. Let me draft up some API-themed poetry and get back to you and we can iterate together from there!

**Comment by rmkubik** [comment]
@nmadadair ah, i forgot to mention we want to try and make this the incanation of the "diviniation spell". So, theming it as like seeing, experiencing, viewing, hearing, etc. would make sense. The goal is to tie "this function parses a string" to the concept of creating a divination spell.

**Comment by nmadadair** [comment]
@rmkubik that's what I understood!

**Comment by nmadadair** [comment]
Divination Spell Incantation

Oh, great creators of The Cloud, let me apply
This divination spell, newly formed through a simple phrase,
Strung together thanks to a most helpful API,
That my requests may return the knowledge I seek
To open my mind to the tower’s supply
Of resources both clear and covert.
For the final door shall stay locked until I am able to scry
The programmable answers that will remove this haze
From my querent and magical eye.

@rmkubik Here's a draft!
I used the Magic 9 poetic form: ABACADABA

**Comment by nmadadair** [comment]
Any of the adjectives here could be replaced with other words (antonyms or just incorrect words)! e.g. simple - complex / helpful - awful / clear - dull / querent - careless / magical - questionable.

**Comment by MarvelProgramming** [comment]
@rmkubik 
> Can you investigate what it would take to actually import a library in our example code @MarvJohnson?
> 
> The only things I know we import are full on published NPM modules and library built ins... We could certainly think about publishing a module for this. Or doing a local import, but I don't know what our options are off the top of my head. It's important to check that any import works both when running it in the QuestIDE _and_ via Validator Hack execution.
> 
> Currently, those 2 systems evaluate in different methods! So sometimes a thing will work in one, but not the other.

The _QuestIDE_ depends on a [runner](https://github.com/twilio/twilioquest/blob/3.2_next/public/code_runner/runner.js#:~:text=require(%27vm,%7D)%3B) that executes user code using the `vm` module. The runner does so by invoking the `runInThisContext` method, which runs the code in the current global context (i.e. the global context where the function is written).

The _Validator Hack_ [finds the `validator.js` file](https://github.com/twilio/twilioquest/blob/3.2_next/src/js/app/components/hack_interface/validator/Validator.jsx#:~:text=const%20validate%20%3D%20await%20requireFromExtension(modulePath)%3B) belonging to the active objective and [runs](https://github.com/twilio/twilioquest/blob/3.2_next/src/js/app/components/hack_interface/validator/Validator.jsx#:~:text=validate\(helper%2C%20helper.validationCallback\)%3B) that. The Validators that execute external user code (more specifically Javascript code) also use the `vm` module.

In both modes of code execution we could introduce an API by setting/appending the context the `vm` instance uses. This approach wouldn't work for python code (?which I'm not sure we're concerned about?), since we spawn a shell and execute the user's code using their python installation, instead of using `vm`. 

One idea I have is to create a separate `.js` file, one that houses **all** of the possible members of the API that we'd want the user to have (we could default this to none, or even come up with a set of members that should always be available), and export that as an object. Then in the `objective.json` file of each objective, define which of those members should be made accessible through something like an `api_members` property. Lastly, just before we append the API members to either `vm` context, we prune the members that weren't defined in the `objective.json` file of the current objective. This would mean the context of existing objectives would be unaffected, and objectives where the `api_members` property was defined would have additional functionality made available.

Let me know what we think and if there are any ideas for better ways to do this!

\*UPDATE\*: This has been solved in [twilio/twilioquest#901](https://github.com/twilio/twilioquest/issues/901)

**Comment by rmkubik** [comment]
I think https://github.com/twilio/twilioquest/issues/901 is our fix for the last comment. Is that correct @MarvJohnson?

**Comment by MarvelProgramming** [comment]
> I think [twilio/twilioquest#901](https://github.com/twilio/twilioquest/issues/901) is our fix for the last comment. Is that correct @MarvJohnson?

Yep! Went ahead and updated the original comment as well

**Comment by MarvelProgramming** [comment]
This is done as of #55. Closing!
