### ISSUE TITLE
The Magic Key in the catacombs is interactable while still hidden

### ISSUE THREAD

**Issue by rmkubik** [TwilioQuest/twilioquest-api-academy#5]
The Magic Key in the catacombs should not be interactable or visible until all 4 statues are completed.

This is likely caused by the key in Tiled having the `hidden` and `interactable` properties both set. TQ doesn't have an interaction this situation handled. `hidden` being true triggers the `hide` function of SpriteObject to be called. This disables the body of the hidden object. However, getInRangeTarget of the SpriteObject does not appear to check if a potential interactable object is hidden or if the body is disabled. 

I think this is an edge case overlooked during the implementation of `interactable` as a separate attribute. When I pulled this into its own ability to allow further specialized objects, I did not consider this implication.

I _think_ a logical solution is for getInRange target to consider the `hidden` property of the considered object. I can see this being undesirable in some cases though... I also worry this would break some old content I'm not aware of. Additionally, when this sort of boolean edge casey stuff starts happening I think it's a code smell that we should be thinking about some sort of state based solution. However, that is very unclear to me without a lot more consideration how we'd make this change.

**Comment by MarvelProgramming** [comment]
I think the potential for things breaking remains whether we modify the getInRange method or take a state based approach. One (temporary) solution might be to add _another_ property that's specifically for preventing interactions while an object is hidden. This way, older objects that expect this behavior aren't effected and the bug will be fixed in the meantime.

I do wonder, though, what a stateful implementation would look like. Would it mean replacing existing properties for a sort of "all-in-one" property that simply holds the name of the initial state? For example, instead of having two properties for `hidden` and `interactable`, we could have `initialState` and set it to something like `hiddenWithoutInteraction`.

Also: while searching for skippable barriers, I stumbled upon an issue with the exclamation point that may be related to this. The plants blocking the path are interactive, but there are interactive fire objects occupying both sides of the walkway that are hidden until the player obtains the _flame of open source_.

https://user-images.githubusercontent.com/51891409/193694392-5c380ad3-ad1d-40c2-a8f3-31cb33f89e8a.mov

**Comment by rmkubik** [comment]
Oh this is an odd bug you found here... I woner if your [PR #817](https://github.com/twilio/twilioquest/pull/817) which I just merged will fix this one actually.

**Comment by rmkubik** [comment]
In retrospect, this might just be "working as intended".

Keeping it simple.
- `hidden` means you can or can not see the object or run into it
- `interactable` means you can spacebar it or not and the exclamation shows up

I think these two properties are just working as intended.

I think maybe we could expand the `hide/show` functions instead.
- hide could take a new param that is called like "disableInteraction"
- show could get an "enableInteraction"
- we could expose these on the `(show/hide)Entities` functions on the world object as a new config object too

**Comment by MarvelProgramming** [comment]
> Oh this is an odd bug you found here... I woner if your https://github.com/twilio/twilioquest/pull/817 which I just merged will fix this one actually.

Looks like this is fixed in the most recent merges

> I think maybe we could expand the hide/show functions instead.

I really like this idea!

> we could expose these on the (show/hide)Entities functions on the world object as a new config object too

Do you mean something like:
```js
// This signature belongs to the showEntities function in world.js
showEntities = (keyOrFilter, timeout = 0, >>>config = {}<<<)
```

where the `config` object would have properties such as `disableInteraction` or `enableInteraction` (perhaps even saying `interaction = true/false` would work)?

**Comment by rmkubik** [comment]
Yeah, I think that config pass in like you have there would work!

Let's use `interactable` to match the property name we use elsewhere!

Double check me here, but I think to maintain current functionality if interactable is undefined then we should make NO changes to the underlying entity's interactable state.

## Theoretical new usages of the api
```js
world.showEntities('flames', undefined, { interactable: false });
```

```js
world.hideEntities('flames', undefined, { interactable: false });
```

**Comment by MarvelProgramming** [comment]
> Double check me here, but I think to maintain current functionality if interactable is undefined then we should make NO changes to the underlying entity's interactable state.

That makes sense to me! I can whip together a branch for this on the TwilioQuest repo soon and link back to this issue

\*UPDATE\*: The GitHub issue for the API proposal lives [here](https://github.com/twilio/twilioquest/issues/892)

**Comment by MarvelProgramming** [comment]
Closing this as it was covered in PR #97 (not the API proposal, just a quick fix for this particular bug)!
